### ISSUE TITLE
Online status is broken

### ISSUE THREAD

**Issue by Textmeister** [pr0crustes/BetterW#17]
The online status feature no longer works.  There is no dot or ring shown to show whether people are online or offline in the recent versions of WhatsApp. Are you able to fix this please?

**Comment by pr0crustes** [comment]
Just fixed it with #18 
Thank you for your feedback, please report if there are any new issues.

**Comment by Textmeister** [comment]
Thanks. Installed 1.17. Resprung and closed WhatsApp out too. However no online indicators show either as dot or ring. Using WhatsApp 2.20.11
