### ISSUE TITLE
Selecting all outgoing messages?

### ISSUE THREAD

**Issue by qmemcpy** [pr0crustes/BetterW#5]
Given that this tweak allows you to delete messages and bypasses time limit, having an option to automatically select all outgoing messages would be great, because that would mean that you can easily select all messages, and delete them at once, effectively erasing your history (from the sender's part, at least).

Could this be done? I'm a programmer myself but have no experience with Objective-C, so even any hint on how to do it would be amazing. (if I manage to do it, I'll add a pull request of course)

**Comment by pr0crustes** [comment]
Delete Subsequent added on #12 should do it. Thanks for the suggestion.
