### ISSUE TITLE
Requesting for update. 

### ISSUE THREAD

**Issue by rwailim** [pr0crustes/BetterW#7]
Hey 

Can you update your tweak to keep it working fine with the latest version for whatsapp 2.19.50

BetterW

**Comment by pr0crustes** [comment]
I've been busy for the last month, sorry for the wait.
It should be working now, the updated version in on my official repo, https://pr0crustes.github.io/repo/ .
If you have any problems, fell free to report them here.
Thanks.

**Comment by rwailim** [comment]
Thanks bro for your kind update  , really its better tweak for whatsapp , much love

**Comment by abir1909** [comment]
Audio to text is a great idea. It’s a shame it’s not working... thanks

Sent from my iPhone

On May 27, 2019, at 2:27 PM, pr0crustes <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #7<https://github.com/pr0crustes/BetterW/issues/7>.
